### ISSUE TITLE
训练时候报错RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by yxt132** [Morizeyao/GPT2-Chinese#65]
我按照作者写的instruction训练斗破苍穹（是txt文件），改了pre_process_data.py，具体改写如下：
def is_default_file_type():
    return False

def load():
    with open("./data/train.txt", 'r', encoding='utf-8') as f:
      print('reading lines')
      lines = f.readlines();
      lines = [line.replace('\n', ' [SEP] ') for line in lines]  
    return lines

用make_vocab.py成功生成了一个50000的词表，
然后运行了train_single.py，运行命令为：

python ./train_single.py \
        --device=1 \
        --model_config=config/model_config_small.json \
        --tokenizer_path=cache/vocab_user.txt \
        --raw_data_path=data/train.txt \
        --raw \
        --epochs=5 \
        --batch_size=1 \
        --lr=1.5e-4 \
        --stride=1023 \
        --output_dir=model/ \
        --pretrained_model='' \
        --segment

模型配置文件model_config_small.json里面的配置为：
{
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 10,
  "n_positions": 1024,
  "vocab_size": 50000
}
这里vocab_size不太清楚应该是50000还是50005？因为加了特殊字符[cls][sep]等

然后成功开始运行，数据也成功处理了，但是运行了一会儿就报错了，具体错误信息为：

Traceback (most recent call last):
  File "./train_single.py", line 235, in <module>
    main()
  File "./train_single.py", line 177, in main
    outputs = model.forward(input_ids=batch_inputs, labels=batch_labels)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_gpt2.py", line 606, in forward
    past=past, head_mask=head_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_gpt2.py", line 523, in forward
    outputs = block(hidden_states, layer_past, head_mask[i])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_gpt2.py", line 345, in forward
    m = self.mlp(self.ln_2(x))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_gpt2.py", line 326, in forward
    h = self.act(self.c_fc(x))
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_gpt2.py", line 102, in gelu
    return 0.5 * x * (1 + torch.tanh(math.sqrt(2 / math.pi) * (x + 0.044715 * torch.pow(x, 3))))
RuntimeError: CUDA error: device-side assert triggered

不太明白问题出在哪里了？请给点建议，另外我的训练语料前需要加[cls] token吗？

谢谢

**Comment by LeeCP8** [comment]
1 词汇表：50000个+5个特殊字符 = 50005个，word_embedding=(50005,768)，你最终的词典是多少个就是多少个，不是文件中词汇个数。
2 训练语料要加[cls]？这个取决于你的目的，如果你想在文本中以[cls]分割篇章，那么训练时，模型就会记住这些特征，然后当输出[cls]，就表示是一个篇章结尾，那么生成时，我们就可以人为截断。

**Comment by LeeCP8** [comment]
另外，你如果添加了特殊标记，请注意检查：[cls]是被分成一个词还是，三个，亦或者5个。

**Comment by yxt132** [comment]
谢谢你的详细回复，[cls]是一个词。不过这些小问题都不是报错的真正原因，有点困惑

**Comment by Morizeyao** [comment]
试试看不要用pre_process_data.py，直接改好train.json然后输入给train_single.py

**Comment by Morizeyao** [comment]
也就是说config里vocab size改成50005还是不行吗？报错内容还是一样的？

**Comment by yxt132** [comment]
不好意思，之前忘记改成50005了，现在改成50005了，目前运行正常。如果有报错再更新。谢谢二位！

**Comment by LeeCP8** [comment]
作者，试试不用per_process_data.py！提交之前，我说过，没有更改过任何你的代码逻辑，词表不一致，运行了一会，挂掉了的，基本就是词表的问题，因为只有当找不到指定索引对应的向量时，才会出现问题。我建议作者回滚到你所谓的Stable版本~

**Comment by Morizeyao** [comment]
所以说众口不调嘛，这个pre_process_data.py以及很多其他功能都不是我加的，是大家的PR。我个人觉得是没有必要，所以才特意留的stable，现在这样确实有点乱了。

**Comment by LeeCP8** [comment]
很好，我也觉得没有必要，所以能不能回滚到你原来的Stable版本

**Comment by Morizeyao** [comment]
不用，我去把他手动删掉吧，stable之后加了一些东西还是有意义的，比如说colab notebook和金庸生成还不错

**Comment by LeeCP8** [comment]
谢谢，顺便把我提交的快速生成整合也删掉，这个很容易实现的，修改你的Stable版本，也只修改ReadMe就可以了，谢谢！

**Comment by yxt132** [comment]
我是刚刚才开始用这个gpt2-chinese，很感谢二位的热心和及时恢复。
我有个疑问，如果不要那个preprocess函数，作者是如何处理不同训练数据格式的呢？还有编码问题？

**Comment by Morizeyao** [comment]
编码的话，统一使用utf-8
训练数据格式的话，请自己编写python或是其他语言脚本将数据源改为本项目需要的数据格式，即一个json列表

**Comment by LeeCP8** [comment]
哈哈，所有数据都处理成json列表，作者，要删除的话，就删干净一些，最好的方式就是将后面两位朋友添加的代码，放进Stable版本里面，也就几行代码而已。恢复你自己觉得能跑就行的代码！

**Comment by Morizeyao** [comment]
........我应该删完了吧，那哥们（我也不记得是谁了）貌似就加了这么点。其他的功能是其他的功能。

**Comment by LeeCP8** [comment]
@yxt132 ，建议你可以看一下pytorch-transformer中的代码，这个库基本就是从里面修改而来的，你可以看看作者的Stable版本，然后根据自己想要的东西去修改，只要你拥有大学本科的所应该掌握知识，肯定可以看懂所有逻辑，建议可以到知乎看一些专业人士的文章！谢谢。

**Comment by LeeCP8** [comment]
你把自定义数据类型删除了，但是ReadMe不删？你只要恢复到你原来的Stable版本就可以，后面朋友添加的，除了我的，代码不多，谢谢！

**Comment by Morizeyao** [comment]
哈哈，说的对，我把ReadMe删一下

**Comment by yxt132** [comment]
@LeeCP8 谢谢你的建议，我好好研究一下。

**Comment by yxt132** [comment]
更新一下，模型跑了5个epoch，我测试了一下，用的generate_texts.py，报错了，信息如下：

Namespace(articles_per_title=5, device='1', length=500, model_config='config/model_config_small.json', model_path='model/final_model', no_wordpiece=False, save_path='generated/', segment=True, temperature=1, titles='\udce9\udc99\udc88\udce5\udcae\udc87', titles_file='', tokenizer_path='cache/vocab_user.txt', topk=8, topp=0)
Model loaded succeed
Traceback (most recent call last):
  File "./generate_texts.py", line 193, in <module>
    main()
  File "./generate_texts.py", line 136, in main
    titles = args.title.split()  # \u5217\u8868\uff0c\u91cc\u9762\u6bcf\u4e2a\u5143\u7d20\u662f\u4e00\u4e2a\u751f\u6210\u7684\u6807\u9898
AttributeError: 'Namespace' object has no attribute 'title'

应该是中文编码的问题， 因为我在运行代码时参数 --title="陈宇"， 然后代码解析成了某种编码。
请问这里应该怎么处理中文？ 是需要修改我们的linux配置文件吗？我用的是ubuntu

**Comment by Morizeyao** [comment]
generate.py能跑吗？

**Comment by yxt132** [comment]
试了一下，也报错了，不过错误稍微有点不一样：

Namespace(batch_size=1, device='1', fast_pattern=False, length=500, model_config='config/model_config_small.json', model_path='model/final_model', no_wordpiece=False, nsamples=4, prefix='\udce9\udc99\udc88\udce5\udcae\udc87', save_samples=False, save_samples_path='.', segment=True, temperature=1, tokenizer_path='cache/vocab_user.txt', topk=8, topp=0)
Model loaded succeed
  0%|                                                                                                                                                                               | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./generate.py", line 213, in <module>
    main()
  File "./generate.py", line 181, in main
    temperature=temperature, top_k=topk, top_p=topp, device=device
  File "./generate.py", line 114, in generate
    return sample_sequence(model, context, length, n_ctx, temperature=temperature, top_k=top_k, top_p=top_p, device=device)
  File "./generate.py", line 79, in sample_sequence
    **inputs)  # Note: we could also use 'past' with GPT-2/Transfo-XL/XLNet (cached hidden-states)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_gpt2.py", line 606, in forward
    past=past, head_mask=head_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_gpt2.py", line 501, in forward
    input_ids = input_ids.view(-1, input_ids.size(-1))
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0]

**Comment by Morizeyao** [comment]
问题貌似出在编码上，要切换成utf-8。考虑到你的python应该是3，那可能是要改ubuntu的系统编码了

**Comment by yxt132** [comment]
刚才把ubuntu的编码改了，现在generate.py可以了，但是generate_text.py还是报错。发现是第136行有个小bug，titles = args.title.split() 应该是titles = args.titles.split()。改过之后就好了。作者可以把这个bug fix一下。另外，生成的样本好多 [UNK]， 也许是我训练时间不够？目前只训练了5个epoch

**Comment by Morizeyao** [comment]
unk的话，你可以通过在生成的时候屏蔽unk对应的logit来去除

**Comment by yxt132** [comment]
好的，谢谢

**Comment by lioyou** [comment]
> 刚才把ubuntu的编码改了，现在generate.py可以了，但是generate_text.py还是报错。发现是第136行有个小bug，titles = args.title.split() 应该是titles = args.titles.split()。改过之后就好了。作者可以把这个bug fix一下。另外，生成的样本好多 [UNK]， 也许是我训练时间不够？目前只训练了5个epoch

思考一下：UNK怎么来的，GPT2的自回归模型，是逐字生成的，shape=(batch_size, sequence_length, config.vocab_size)，最终生成时shape = (1,1024,50005)，通过概率计算，从50005个位置中选，为什么选中UNK对应的索引，说明你训练的时候，语料中有许多UNK，换个说法，就是分词时，产生了许多词表中没有的词。如果你采用作者说的：屏蔽logit去除，结果。。。

**Comment by yxt132** [comment]
谢谢指点!

**Comment by fengzuo97** [comment]
device-side assert triggered， 可能是服务器有多块gpu时，没有默认使用第一块gpu，指定使用其他的gpu导致的，要么默认使用第1块gpu，或者使用全部gpu，如果要分别使用其他gpu，在运行程序时，加入CUDA_VISIABLE命令指定gpu。
